# Generated by Django 4.0.2 on 2022-02-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_history_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_image',
            field=models.ImageField(default='book_pic/default.png', upload_to='book_pic'),
        ),
    ]
