# Generated by Django 4.0.2 on 2022-02-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/home/user/PycharmProjects/book_recommendation/media/default.png', upload_to='profile_pics'),
        ),
    ]
